### PR TITLE
FIX: Fixes

### LINKED ISSUE #1: 'module' object has no attribute 'GL_RGBA32F_ARB'
I'm getting this traceback running `demo-arc.py`.

I have PyOpenGL 3.1.0a1 (what `pip` installed for me today).  This is Python 2.7 on Fedora 18.

Am I doing something wrong here?  Is there anything else that would be useful for debugging purposes?

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "demo-arc.py", line 38, in on_display
    paths.draw()
  File "/home/mdboom/python/lib/python2.7/site-packages/glagg/collection.py", line 349, in draw
    self.upload()
  File "/home/mdboom/python/lib/python2.7/site-packages/glagg/collection.py", line 329, in upload
    gl.glTexImage2D( gl.GL_TEXTURE_2D, 0, gl.GL_RGBA32F_ARB,
AttributeError: 'module' object has no attribute 'GL_RGBA32F_ARB'
```

### PR DESCRIPTION
**Pull request by Eric89GXL**
@rougier this was (just about) the minimum required to get `gl-agg` running on my OSX laptop. I tried installing it on Ubuntu earlier today (before making these changes) and that didn't work either, I can see if these changes fix that, too.

Closes #1.

### CODE REVIEW

**Comment by rougier** [comment]
Ooops, totally forget this PR. Is it worth merging it ?

**Comment by Eric89GXL** [comment]
Not sure actually, it's from a long time ago so I don't really remember.

**Comment by rougier** [comment]
Ok. Sorry to not have answered sooner.

**Comment by Eric89GXL** [comment]
No problem, I'm just cleaning out the old PRs

**Pull request closed without merging**
